// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBv_A3PDkoBpTp-DwCL5YqYP_ua6lmYmYE',
    appId: '1:497710077159:android:45be50964bedafe2433e42',
    messagingSenderId: '497710077159',
    projectId: 'pmsn2025vae',
    storageBucket: 'pmsn2025vae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB95KOM08ddrF8HESu8twJzRo85pkNyPDQ',
    appId: '1:497710077159:ios:cd21ae2fb0df2256433e42',
    messagingSenderId: '497710077159',
    projectId: 'pmsn2025vae',
    storageBucket: 'pmsn2025vae.firebasestorage.app',
    iosBundleId: 'com.example.pmsn2025',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB95KOM08ddrF8HESu8twJzRo85pkNyPDQ',
    appId: '1:497710077159:ios:cd21ae2fb0df2256433e42',
    messagingSenderId: '497710077159',
    projectId: 'pmsn2025vae',
    storageBucket: 'pmsn2025vae.firebasestorage.app',
    iosBundleId: 'com.example.pmsn2025',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLtJGxbNW4we0cumjL8KR2af2eXaBh00U',
    appId: '1:497710077159:web:d493fe21876d04a8433e42',
    messagingSenderId: '497710077159',
    projectId: 'pmsn2025vae',
    authDomain: 'pmsn2025vae.firebaseapp.com',
    storageBucket: 'pmsn2025vae.firebasestorage.app',
    measurementId: 'G-QFLS4X2S39',
  );

}